POST http://localhost:3000/blogs/add
Content-Type: application/json

{
    "title": "IFPE Belo Jardim abre inscrições para cursos de extensão na área de música",
    "content": "O curso de Licenciatura em Música do IFPE Belo Jardim abriu, nesta segunda-feira (12), inscrições para oito cursos de extensão na área de música. Os cursos básicos são nas áreas de canto, guitarra, saxofone, clarinete, teoria musical, trompete, flauta e bandas marciais.",
    "status": 0
}

###

